SELECT COUNT(PLAYERS_TURNS.ID) AS NUMBER_OF_TURNS, PLAYERS.NAME
FROM PLAYERS
INNER JOIN PLAYERS_TURNS
ON PLAYERS.ID = PLAYERS_TURNS.PLAYERS_ID
GROUP BY PLAYERS_TURNS.PLAYERS_ID, PLAYERS.NAME
ORDER BY NUMBER_OF_TURNS DESC
FETCH NEXT 1 ROWS ONLY;
