@startuml Logic Diagram
    Object Players {
        id
        player_type
        name
        winnings
        losses
        ties
    }
    Object Players_Types {
        id
        type
    }
    Object Games {
        id
        name
        number_of_turns
        number_of_players
    }
    Object Players_Turns {
        id
        turn_id
        player_id
        is_last_move
        is_winner
    }
    Object Turns {
        id
        game_id
        is_finished
    }
    Object TicTacToe_Turns {
        id
        player_x
        player_o
    }
    Object HangMan_Turns {
        id
        player_giver
        player_guesser
    }
    Object Boards {
        id
        tictactoe_turn_id
        is_full
    }
    Object Squares {
        board_id
        x_position
        y_position
        piece
    }
    Object HangedMen {
        id
        hangman_turn_id
        is_dead
        is_saved
    }
    Object SecretLetters {
        hangedman_id
        letter
        position
        is_shown
    }

    Players_Types --o{ Players

    Players -left-o{ Players_Turns

    Games --o{ Turns
    
    Turns -right-|{ Players_Turns

    Players_Turns --|{ TicTacToe_Turns
    Players_Turns --|{ TicTacToe_Turns

    Players_Turns --|{ HangMan_Turns
    Players_Turns --|{ HangMan_Turns

    TicTacToe_Turns --o{ Boards

    Boards --|{ Squares

    HangMan_Turns --o{ HangedMen

    HangedMen --|{ SecretLetters

@enduml
