@startuml Logic Diagram
    Entity Players {
        * id : int <<generated>>
        --
        * player_type : id <<FK>>
        * name : str
          winnings : int
          losses : int
          ties : int
    }
    Entity Players_Types {
      * id : int <<generated>>
      --
      * type : str
    }
    Entity Games {
        * id : int <<generated>>
        --
        * name : str
        * number_of_turns : int
        * number_of_players : int
    }
    Entity Players_Turns {
        * id : int <<generated>>
        --
        * turn_id : int <<FK>>
        * player_id : int <<FK>>
          is_last_move : boolean
          is_winner : boolean
    }
    Entity Turns {
        * id : int <<generated>>
        --
        * game_id : int <<FK>>
          is_finished : boolean
    }
    Entity TicTacToe_Turns {
        * id : int <<generated>>
        --
        * player_x : int <<FK>>
        * player_o : int <<FK>>
    }
    Entity HangMan_Turns {
        * id : int <<generated>>
        --
        * player_giver : int <<FK>>
        * player_guesser : int <<FK>>
    }
    Entity Boards {
        * id : int <<generated>>
        --
        * tictactoe_turn_id : int <<FK>>
          is_full : boolean
    }
    Entity Squares {
        * board_id : int <<FK>>
        * x_position : int
        * y_position : int
          piece : str 
    }
    Entity HangedMen {
        * id : int <<generated>>
        --
        * hangman_turn_id : int <<FK>>
          is_dead : boolean
          is_saved : boolean
    }
    Entity SecretLetters {
        * hangedman_id : int <<FK>>
        * letter : str
        * position : int
          is_shown : boolean
    }

    Players_Types --o{ Players

    Players -left-o{ Players_Turns

    Games --o{ Turns
    
    Turns -right-|{ Players_Turns

    Players_Turns --|{ TicTacToe_Turns
    Players_Turns --|{ TicTacToe_Turns

    Players_Turns --|{ HangMan_Turns
    Players_Turns --|{ HangMan_Turns

    TicTacToe_Turns --o{ Boards

    Boards --|{ Squares

    HangMan_Turns --o{ HangedMen

    HangedMen --|{ SecretLetters

@enduml
